services:
  postgis:
    image: kartoza/postgis:latest
    restart: no
    container_name: postgis
    environment:
      POSTGRES_USER: gis
      POSTGRES_PASSWORD: Jesepa@1234
      POSTGRES_DB: gis
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  geoserver:
      image: kartoza/geoserver
      restart: always
      container_name: geoserver
      environment:
        - GEOSERVER_ADMIN_USER=admintest
        - GEOSERVER_ADMIN_PASSWORD=geoservertest
      ports: 
        - "8080:8080"
      depends_on: 
        - postgis   
      volumes:
       #- geoserver_data:/usr/local/tomcat/webapps/geoserver/WEB-INF
       - ./geoserver_xml/web.xml:/usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
       - ./geoserver_data_dir:/opt/geoserver/data_dir 

       
  nginx-geo:
    image: nginx:latest
    restart: always
    container_name: nginx-geo
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ./nginx_html/index.html:/usr/share/nginx/html/index.html
      - ./nginx_conf/nginx.conf:/etc/nginx/conf.d/default.conf
        

volumes:
  postgis_data:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: ./postgis_data
  geoserver_data:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: ./geoserver_data
  nginx_html:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: ./nginx_html                    